### ISSUE TITLE
Linux Mint: "The URL can’t be shown"

### ISSUE THREAD

**Issue by jgibbons94** [hyperdriveguy/OpenGospel#24]
On Linux Mint 19 the ./scriptures.py command shows the message "The URL can’t be shown."

Workaround: Use the command ${PWD}/scriptures.py

Possible cause:
On Linux Mint, os.path.dirname returns '.' which does not work with WebKit URLs.

Possible solutions: 
-Use a different method that returns the full path (maybe os.path.getcwd() or os.path.abspath) for early development
-Add a configuration option for the full path pointing to the directory containing the scriptures later in development (to make it more user-friendly)

**Comment by hyperdriveguy** [comment]
Fixed by #25
